language: python
dist: trusty
python:
  - "3.6"
  - "3.5"
  
cache: pip

install: pip install -e .[dev]

script: py.test --cov=lanlytics_api_lib

after_success: bash <(curl -s https://cov.lanlytics.com/bash) -t "zvYVxfDUQ2Swtbv11JFS" -r nisac/lanlytics-api-lib
